### PR TITLE
Refactor url code to better align with SEC API

### PR DESCRIPTION
**Pull request by jordan-gillard**
This PR updates the examples in the repository's README.md file to wrap exact phrase searches in single quotes. This provides a cross-platform way to search for exact phrases on both Unix and Windows-based machines.

Resolves: #24

### CODE REVIEW

**Comment by GalenReich** [comment]
Unfortunately this didn't work for me, the tool still behaves as if there was no quoting:

```shell
edgar-tool text_search '"Tsunami Hazards"'
```

makes requests to: `https://efts.sec.gov/LATEST/search-index?q=Tsunami+Hazards` (note the lack of url encoded quotes)

**Comment by jordan-gillard** [comment]
@GalenReich Ahh my bad. I just ran through it with a debugger and figured it out in https://github.com/bellingcat/EDGAR/pull/36/commits/549273e4e79cbde1e3bf4192140adc8d920aeddf

In order to make the debugger easy to use I had to rename `main.py` to `__main__.py` and run the directory as a module.

The above changes will fix the issue for now. Users will need to wrap their already quoted phrase in another single quote, like in your example (`edgar-tool text_search '"Tsunami Hazards"'`). But, it would be friendlier if we could allow users to just use quotes once, like this:

```
edgar-tool text_search "John Doe" Pharmaceuticals Chemicals
```

We can't because of an issue related to how `fire` interprets the command line arguments, and then how those arguments are parsed before the call to `urlencode`. 

For example, if I call the CLI without using the single quote then double quote pattern, `'"..."'`

```shell
edgar-tool text_search "John Doe" Pharmaceuticals Chemicals
```

Then `keywords` equals `('John Doe', 'Pharmaceuticals', 'Chemicals')` in `SecEdgarScraperCli.text_search` https://github.com/bellingcat/EDGAR/blob/20c5d58eaf45bc1c84e9e889f73225f79f8aa8c3/edgar_tool/cli.py#L73-L77

Which is then joined into the single string `'John Doe Pharmaceuticals Chemicals'` in `EdgarTextSearcher._generate_request_args` here:
https://github.com/bellingcat/EDGAR/blob/20c5d58eaf45bc1c84e9e889f73225f79f8aa8c3/edgar_tool/text_search.py#L216-L217

We can fix this so that the code understands that a string with a space character, like `'John Doe'` but not `'Pharmaceuticals'`, should be parsed as an exact phrase. I can do this in a follow-up PR.

**Comment by GalenReich** [comment]
The desired behaviour is that a search for `"Tsunami Warning"` will give requests where `q=%22Tsunami+Warning%22`

At the moment there is some double escaping going on and (in Powershell) the space is doubly escaped, but the quotes are missed: `q=Tsunami%2520Warning`

You've given me some ideas about solving this at the join - I'll push a commit or two in a sec

**Comment by GalenReich** [comment]
I think that solves it - the machinery was already mostly working because of the urlencode here:

https://github.com/bellingcat/EDGAR/blob/20c5d58eaf45bc1c84e9e889f73225f79f8aa8c3/edgar_tool/text_search.py#L249

Those changes implement your suggestion of wrapping space-containing keywords in quotes, which also solves the escaping problem. Thanks for pointing out how `fire` parsed the keywords - super helpful!

Let me know what you think!

**Comment by jordan-gillard** [comment]
@GalenReich haha man, it's your repo! If you think the PR is good to go then merge away 😎

I'll take a closer look at your commits tomorrow - but I trust ya! Im embarrassed that I didn't actually solve the issue and encoded the URL twice. I code like sh*t without TDD. It's my kryptonite.

**Comment by jordan-gillard** [comment]
Converted to a draft while I flesh out the URL generation code. Will wrap this up tomorrow.

**Comment by GalenReich** [comment]
Hey @jordan-gillard I finally managed to close pr/40 - once again really sorry about the delay! Can this be closed as a duplicate now?

**Comment by jordan-gillard** [comment]
@GalenReich I'll give everything a deeper look later and get back to ya!

**Comment by jordan-gillard** [comment]
Closing. I'll get caught up with recent work and plan the next contribution :)

**Pull request closed without merging**
